vaadin:
    launch-browser: 'true'
    whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
spring:
    devtools:
      restart:
          enabled: false
    mustache:
        check-template-location: 'false'
    jpa:
        defer-datasource-initialization: 'true'
logging:
    level:
        org:
            atmosphere: warn
server:
    port: ${PORT:8080}

io.sapl:
    server:
        accesscontrol:
            encoded-admin-password: "$argon2id$v=19$m=16384,t=2,p=1$4paxgjEMXUrSjKeEEh3+7g$o7oeFzAaNtPSuM6kbEmK+1js2bLlpbqAcgYvImeEgsA"
            admin-username: "user"
